languageCode = "en"
languageName = "English"
weight = 1
title = "mnjm.github.io"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "imgs/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Hey, I'm Manjunath Mohan, and this is my personal site where I share insights and how-tos, mostly centered around the tech/dev world, which continually piques my curiosity."
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Manjunath Mohan"
  image = "imgs/portrait.webp"
  headline = "Hi! Welcome to my site"
  bio = "I’m a Software Engineer based in Bengaluru, India, specializing in Computer Vision and Deep Learning. My interests extend to AI, Sensor Fusion, Motion Capturing, Linux and FOSS"
  links = [
    { email = "mailto:mnjm@duck.com" },
    { link = "https://mnjm.github.io/about/" },
    { github = "https://github.com/mnjm" },
    { linkedin = "https://www.linkedin.com/in/mnjm/" },
    { medium = "https://medium.com/@mnjm" },
    { dev = "https://dev.to/mnjm" },
    { stack-overflow = "https://stackoverflow.com/users/14183388/manjunath-mohan" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { bluesky = "https://bsky.app/profile/username" },
#     { codepen = "https://codepen.io/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
#     { itch-io = "https://username.itch.io" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
#     { x-twitter = "https://twitter.com/username" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
  ]
